version: "3.8"

services:
  app:
    build:
      args:
        user: smkn4bdg
        uid: 2025
      context: ./
      dockerfile: Dockerfile
    image: smkn4bdg
    container_name: cms_smkn4bdg-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - smkn4bdg
    depends_on:
      - db

  db:
    image: mysql
    container_name: cms_smkn4bdg-db
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - smkn4bdg

  nginx:
    image: nginx:alpine
    container_name: cms_smkn4bdg-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - smkn4bdg
    depends_on:
      - app

networks:
  smkn4bdg:
    driver: bridge
